export const ROLES = ['Doctor', 'Nurse', 'Surgeon', 'Pharmacist', 'Medical Researcher', 'Lab Technician', 'Paramedic'] as const;

export const PROMPTS: Record<typeof ROLES[number], string> = {
  Doctor: "Transform this person into a professional, friendly doctor in a modern hospital setting, captured in a dynamic and engaging pose like consulting a tablet or speaking with a patient. Change their clothes to a crisp white lab coat over professional attire, and add a stethoscope draped around their neck. The background should be a bright, clean, and slightly blurred doctor's office or hospital hallway.",
  Nurse: "Turn this person into a compassionate nurse wearing modern, comfortable scrubs (in a calming blue or green color), shown in a caring pose like checking a chart or comforting a patient. Give them a warm, reassuring expression. The background should be a welcoming hospital ward or a patient's room, with a soft, out-of-focus background.",
  Surgeon: "Convert this person into a focused surgeon in an operating room, captured in a moment of concentration or action. Dress them in full surgical scrubs, including a cap and mask (pulled down to show their face clearly). The background should be a high-tech, well-lit operating theater with medical equipment visible but blurred.",
  Pharmacist: "Change this person into a knowledgeable pharmacist standing behind a counter in a clean, well-organized pharmacy, pictured as if they are explaining a medication or organizing prescriptions. They should be wearing a professional white lab coat. The background should feature shelves neatly stocked with medicine boxes, creating a professional and trustworthy environment.",
  'Medical Researcher': "Reimagine this person as a dedicated medical researcher in a state-of-the-art laboratory, captured in a thoughtful pose looking at a microscope or analyzing data on a screen. Dress them in a lab coat over smart-casual clothing. The background should be a modern lab with scientific equipment, beakers, and monitors, all slightly out of focus.",
  'Lab Technician': "Transform this person into a meticulous lab technician, posed as if carefully handling a test tube or operating a complex machine. They should be wearing safety goggles and a lab coat. The background should be a busy but organized clinical laboratory with various scientific instruments.",
  Paramedic: "Convert this person into a heroic paramedic in action, possibly kneeling by a medical bag or standing next to an ambulance with a determined expression. Dress them in a professional paramedic uniform. The background should be an out-of-focus urban or suburban environment, suggesting an emergency scene."
};